### ISSUE TITLE
Sorry to bother, but ShuffleNet encounters some problem.

### ISSUE THREAD

**Issue by HolmesShuan** [KeyKy/model-zoo#1]
Hi, I have created ShuffleNet repository recently, but unfortunately it has some logical bug in it. We decided to delete in case some unknown bugs. Before that u have forked this repository, we sincerely hope u to delete this wrong repository. Many thanks. (We can't find a better way to make contact with u. Sorry about this issue comment.)

**Comment by HolmesShuan** [comment]
@KeyKy

**Comment by KeyKy** [comment]
OK. @HolmesShuan

**Comment by HolmesShuan** [comment]
Many thanks. :+1:
