### ISSUE TITLE
How to set parameters when training mobilenet on imagnet1k

### ISSUE THREAD

**Issue by BoXiao123** [KeyKy/model-zoo#2]
Hi @KeyKy , I am trying to train mobilenet on imagnet1k by using mxnet. However I can get only 0.30 train accuracy after 5 epoch and this value did not change after. So how to set the parameters like learning rate, scale, and RGB mean in order to get similar training result in the model zoo?

**Comment by KeyKy** [comment]
@BoXiao123 I do not train the mobilenet. It was converted from caffe version https://github.com/shicai/MobileNet-Caffe
